<?php

namespace App\Admin;

/** Settings screen: one tab per group of fields (keys match the JSON in the settings table). */
class SettingsTabs
{
    public static function all(): array
    {
        $pageKeys = ['home' => 'Homepage', 'services' => 'Services', 'fleet' => 'Fleet', 'coverage' => 'Coverage', 'blog' => 'Blog', 'about' => 'About', 'contact' => 'Contact', 'faq' => 'FAQ'];
        $pageSeo = [];
        foreach ($pageKeys as $k => $name) {
            $pageSeo[] = ['type' => 'section', 'title' => $name];
            $pageSeo[] = ['k' => "pages.$k.title", 'label' => 'Meta title', 'type' => 'text', 'full' => true];
            $pageSeo[] = ['k' => "pages.$k.description", 'label' => 'Meta description', 'type' => 'textarea'];
            $pageSeo[] = ['k' => "pages.$k.keywords", 'label' => 'Meta keywords', 'type' => 'text', 'full' => true];
            $pageSeo[] = ['k' => "pages.$k.ogImage", 'label' => 'Share image', 'type' => 'image'];
        }
        $toggle = fn ($k, $label, $help) => ['k' => $k, 'label' => $label, 'type' => 'toggle', 'help' => $help];

        return [
            'general' => ['group' => 'general', 'label' => 'Branding & logo', 'icon' => 'i-image', 'desc' => 'Logo, favicon, site name and footer text.', 'fields' => [
                ['type' => 'section', 'title' => 'Logo', 'desc' => 'Upload a PNG or SVG logo with a transparent background. Without a logo, the two-colour text wordmark below is shown.'],
                ['k' => 'logo', 'label' => 'Logo', 'type' => 'image'],
                ['k' => 'logoHeight', 'label' => 'Logo height (px)', 'type' => 'number', 'help' => 'desktop header, 28–64'],
                $toggle('showWordmarkWithLogo', 'Wordmark next to logo', 'Also show the text name beside the logo'),
                ['k' => 'favicon', 'label' => 'Favicon (browser tab icon)', 'type' => 'image', 'help' => 'square PNG/ICO, 512×512 recommended'],
                ['type' => 'section', 'title' => 'Name'],
                ['k' => 'siteName', 'label' => 'Business / site name', 'type' => 'text'],
                ['k' => 'tagline', 'label' => 'Tagline under the wordmark', 'type' => 'text'],
                ['k' => 'brandFirst', 'label' => 'Wordmark — first part (dark)', 'type' => 'text'],
                ['k' => 'brandSecond', 'label' => 'Wordmark — second part (red)', 'type' => 'text'],
                ['k' => 'siteUrl', 'label' => 'Live website URL', 'type' => 'url', 'help' => 'e.g. https://busestransport.com — used for sitemap & SEO', 'full' => true],
                ['type' => 'section', 'title' => 'Footer & layout'],
                ['k' => 'footerAbout', 'label' => 'Footer description', 'type' => 'textarea'],
                ['k' => 'footerLegal', 'label' => 'Footer small print', 'type' => 'text', 'full' => true],
                ['k' => 'copyright', 'label' => 'Copyright line', 'type' => 'text', 'full' => true, 'help' => '{year} becomes the current year'],
                $toggle('showFloatingWhatsApp', 'Floating WhatsApp button', 'Show the round WhatsApp button on every page'),
                $toggle('showBlogInNav', 'Blog in menu', 'Show “Blog” in the header and footer'),
            ]],
            'contact' => ['group' => 'contact', 'label' => 'Contact details', 'icon' => 'i-phone', 'desc' => 'Phone numbers, WhatsApp, email, address and hours — used across the whole site.', 'fields' => [
                ['k' => 'phones', 'label' => 'Phone numbers', 'type' => 'strings', 'help' => 'one per line — the first is the main number'],
                ['k' => 'emails', 'label' => 'Email addresses', 'type' => 'strings', 'help' => 'one per line'],
                ['k' => 'whatsapp', 'label' => 'WhatsApp number', 'type' => 'text', 'help' => 'with country code, e.g. +971 52 736 6525'],
                ['k' => 'headStripLocation', 'label' => 'Top bar location text', 'type' => 'text'],
                ['k' => 'whatsappMessage', 'label' => 'WhatsApp greeting message', 'type' => 'textarea', 'help' => 'pre-filled when visitors tap WhatsApp'],
                ['k' => 'address', 'label' => 'Address', 'type' => 'text', 'full' => true],
                ['k' => 'hours', 'label' => 'Hours line', 'type' => 'text', 'full' => true],
                ['k' => 'hoursRows', 'label' => 'Hours table (contact page)', 'type' => 'kv'],
                ['k' => 'mapEmbedUrl', 'label' => 'Google Maps embed URL', 'type' => 'url', 'full' => true, 'help' => 'Google Maps → Share → Embed a map → copy the src="https://www.google.com/maps/embed?…" link'],
                ['k' => 'contactTitle', 'label' => 'Contact page heading', 'type' => 'text', 'full' => true],
                ['k' => 'contactSub', 'label' => 'Contact page intro', 'type' => 'textarea'],
            ]],
            'social' => ['group' => 'social', 'label' => 'Social links', 'icon' => 'i-globe', 'desc' => 'Icons appear in the footer; review links power the homepage reviews section.', 'fields' => [
                ['k' => 'facebook', 'label' => 'Facebook', 'type' => 'url'],
                ['k' => 'instagram', 'label' => 'Instagram', 'type' => 'url'],
                ['k' => 'tiktok', 'label' => 'TikTok', 'type' => 'url'],
                ['k' => 'linkedin', 'label' => 'LinkedIn', 'type' => 'url'],
                ['k' => 'youtube', 'label' => 'YouTube', 'type' => 'url'],
                ['k' => 'x', 'label' => 'X (Twitter)', 'type' => 'url'],
                ['k' => 'googleReviews', 'label' => 'Google reviews / Business Profile link', 'type' => 'url', 'full' => true],
            ]],
            'home' => ['group' => 'home', 'label' => 'Homepage', 'icon' => 'i-grid', 'desc' => 'Every text on the homepage, plus switches to show or hide each section.', 'fields' => [
                ['type' => 'section', 'title' => 'Hero'],
                ['k' => 'heroKicker', 'label' => 'Small label above the heading', 'type' => 'text', 'full' => true],
                ['k' => 'heroLine1', 'label' => 'Heading line 1', 'type' => 'text'],
                ['k' => 'heroLine2', 'label' => 'Heading line 2', 'type' => 'text'],
                ['k' => 'heroHighlight', 'label' => 'Heading line 3 (red)', 'type' => 'text'],
                ['k' => 'heroImage', 'label' => 'Background image', 'type' => 'image'],
                ['k' => 'heroSub', 'label' => 'Intro paragraph', 'type' => 'textarea'],
                ['k' => 'heroPrimaryLabel', 'label' => 'Main button text', 'type' => 'text'],
                ['k' => 'heroPrimaryHref', 'label' => 'Main button link', 'type' => 'text'],
                ['k' => 'heroSecondaryLabel', 'label' => 'Second button text', 'type' => 'text'],
                ['k' => 'heroSecondaryHref', 'label' => 'Second button link', 'type' => 'text'],
                ['k' => 'trust', 'label' => 'Numbers under the buttons', 'type' => 'kv'],
                ['k' => 'quoteTitle', 'label' => 'Quote form title', 'type' => 'text'],
                ['k' => 'quoteBadge', 'label' => 'Quote form badge', 'type' => 'text'],
                ['k' => 'quoteNote', 'label' => 'Quote form note', 'type' => 'text', 'full' => true],
                ['type' => 'section', 'title' => 'Ticker', 'desc' => 'Routes marked “Ticker” in Coverage & routes are shown first.'],
                $toggle('showTicker', 'Show ticker', 'Scrolling strip under the hero'),
                ['k' => 'tickerExtras', 'label' => 'Extra ticker items', 'type' => 'strings', 'help' => 'one per line — “Text|Bold part”'],
                ['type' => 'section', 'title' => 'Services section'],
                $toggle('showServices', 'Show section', 'Services grid'),
                ['k' => 'servicesEyebrow', 'label' => 'Small label', 'type' => 'text'],
                ['k' => 'servicesTitle', 'label' => 'Heading', 'type' => 'text', 'full' => true],
                ['k' => 'servicesSub', 'label' => 'Intro', 'type' => 'textarea'],
                ['type' => 'section', 'title' => 'Fleet section', 'desc' => 'Choose which vehicles appear with the “Homepage & menu” switch in Fleet.'],
                $toggle('showFleet', 'Show section', 'Fleet slider'),
                ['k' => 'fleetEyebrow', 'label' => 'Small label', 'type' => 'text'],
                ['k' => 'fleetTitle', 'label' => 'Heading', 'type' => 'text', 'full' => true],
                ['k' => 'fleetSub', 'label' => 'Intro', 'type' => 'textarea'],
                ['type' => 'section', 'title' => 'Why choose us'],
                $toggle('showWhy', 'Show section', 'Feature grid (also used on the About page)'),
                ['k' => 'whyEyebrow', 'label' => 'Small label', 'type' => 'text'],
                ['k' => 'whyTitle', 'label' => 'Heading', 'type' => 'text', 'full' => true],
                ['k' => 'whySub', 'label' => 'Intro', 'type' => 'textarea'],
                ['k' => 'why', 'label' => 'Features', 'type' => 'features'],
                ['type' => 'section', 'title' => 'Coverage & map'],
                $toggle('showCoverage', 'Show section', 'UAE map, routes and emirates'),
                ['k' => 'coverageEyebrow', 'label' => 'Small label', 'type' => 'text'],
                ['k' => 'coverageTitle', 'label' => 'Heading', 'type' => 'text', 'full' => true],
                ['k' => 'coverageSub', 'label' => 'Intro', 'type' => 'textarea'],
                ['type' => 'section', 'title' => 'Numbers strip'],
                $toggle('showStats', 'Show section', 'Animated numbers'),
                ['k' => 'stats', 'label' => 'Numbers', 'type' => 'stats'],
                ['type' => 'section', 'title' => 'How booking works'],
                $toggle('showSteps', 'Show section', 'Four steps'),
                ['k' => 'stepsEyebrow', 'label' => 'Small label', 'type' => 'text'],
                ['k' => 'stepsTitle', 'label' => 'Heading', 'type' => 'text', 'full' => true],
                ['k' => 'stepsSub', 'label' => 'Intro', 'type' => 'textarea'],
                ['k' => 'steps', 'label' => 'Steps', 'type' => 'steps'],
                ['type' => 'section', 'title' => 'Reviews', 'desc' => 'Shows your testimonials when you have some; otherwise links to Google / Facebook reviews.'],
                $toggle('showReviews', 'Show section', 'Reviews / testimonials'),
                ['k' => 'reviewsEyebrow', 'label' => 'Small label', 'type' => 'text'],
                ['k' => 'reviewsTitle', 'label' => 'Heading', 'type' => 'text', 'full' => true],
                ['k' => 'reviewsSub', 'label' => 'Intro (when there are no testimonials)', 'type' => 'textarea'],
                ['type' => 'section', 'title' => 'Blog'],
                $toggle('showBlog', 'Show section', 'Latest 3 articles'),
                ['k' => 'blogEyebrow', 'label' => 'Small label', 'type' => 'text'],
                ['k' => 'blogTitle', 'label' => 'Heading', 'type' => 'text', 'full' => true],
                ['k' => 'blogSub', 'label' => 'Intro', 'type' => 'textarea'],
                ['type' => 'section', 'title' => 'Call-to-action band', 'desc' => 'Also used at the bottom of most pages.'],
                $toggle('showCta', 'Show section', 'Bottom call-to-action'),
                ['k' => 'ctaTitle', 'label' => 'Heading', 'type' => 'text', 'full' => true],
                ['k' => 'ctaSub', 'label' => 'Text', 'type' => 'textarea'],
                ['k' => 'ctaImage', 'label' => 'Background image', 'type' => 'image'],
            ]],
            'about' => ['group' => 'about', 'label' => 'About page', 'icon' => 'i-users', 'desc' => 'Heading, story and the “at a glance” facts panel.', 'fields' => [
                ['k' => 'title', 'label' => 'Heading', 'type' => 'text', 'full' => true],
                ['k' => 'sub', 'label' => 'Intro', 'type' => 'textarea'],
                ['k' => 'body', 'label' => 'Story', 'type' => 'markdown'],
                ['k' => 'image', 'label' => 'Side image', 'type' => 'image'],
                ['k' => 'panelTitle', 'label' => 'Facts panel title', 'type' => 'text'],
                ['k' => 'valuesTitle', 'label' => 'Features heading', 'type' => 'text'],
                ['k' => 'facts', 'label' => 'Facts', 'type' => 'kv'],
            ]],
            'seo' => ['group' => 'seo', 'label' => 'SEO & meta tags', 'icon' => 'i-search', 'desc' => 'Default meta tags, search engine verification and indexing.', 'fields' => [
                ['k' => 'defaultTitle', 'label' => 'Homepage title tag', 'type' => 'text', 'full' => true],
                ['k' => 'titleTemplate', 'label' => 'Title template for other pages', 'type' => 'text', 'full' => true, 'help' => '%s is replaced by the page title'],
                ['k' => 'description', 'label' => 'Default meta description', 'type' => 'textarea', 'help' => '150–160 characters works best'],
                ['k' => 'keywords', 'label' => 'Default meta keywords', 'type' => 'textarea', 'help' => 'comma separated'],
                ['k' => 'ogImage', 'label' => 'Default social share image', 'type' => 'image', 'help' => '1200×630 recommended'],
                ['k' => 'googleVerification', 'label' => 'Google Search Console code', 'type' => 'text', 'help' => 'content="…" value of the meta tag'],
                ['k' => 'bingVerification', 'label' => 'Bing Webmaster code', 'type' => 'text', 'help' => 'msvalidate.01 value'],
                ['k' => 'businessType', 'label' => 'Business type (schema.org)', 'type' => 'select', 'options' => array_map(fn ($v) => [$v, $v], ['LocalBusiness', 'AutoRental', 'TravelAgency', 'TaxiService', 'Organization'])],
                $toggle('robotsIndex', 'Search engines', 'Allow Google & others to index the site (turn off for a staging copy)'),
            ]],
            'pageseo' => ['group' => 'seo', 'label' => 'Page meta tags', 'icon' => 'i-tag', 'desc' => 'Override the title, description, keywords and share image of each main page. Services, vehicles, posts and pages have their own SEO fields in their editors.', 'fields' => $pageSeo],
            'tracking' => ['group' => 'tracking', 'label' => 'Tracking & code', 'icon' => 'i-chart', 'desc' => 'Analytics tags and custom code added to every public page.', 'fields' => [
                ['k' => 'gtmId', 'label' => 'Google Tag Manager ID', 'type' => 'text', 'help' => 'GTM-XXXXXXX'],
                ['k' => 'ga4Id', 'label' => 'Google Analytics 4 ID', 'type' => 'text', 'help' => 'G-XXXXXXXXXX (skip if GA4 runs through GTM)'],
                ['k' => 'metaPixelId', 'label' => 'Meta (Facebook) Pixel ID', 'type' => 'text', 'help' => 'numbers only'],
                ['k' => 'headCode', 'label' => 'Custom code in <head>', 'type' => 'code', 'help' => 'verification tags, chat widgets…'],
                ['k' => 'bodyCode', 'label' => 'Custom code at end of <body>', 'type' => 'code'],
            ]],
            'email' => ['group' => 'email', 'label' => 'Email alerts', 'icon' => 'i-mail', 'desc' => 'Get an email for every new quote request. Works with Gmail (App Password), Zoho, Hostinger or your cPanel email.', 'fields' => [
                $toggle('notifyEnabled', 'Email alerts', 'Email me when a quote request arrives'),
                ['k' => 'notifyTo', 'label' => 'Send alerts to', 'type' => 'email'],
                ['k' => 'smtpHost', 'label' => 'SMTP host', 'type' => 'text', 'help' => 'e.g. smtp.hostinger.com or mail.yourdomain.com'],
                ['k' => 'smtpPort', 'label' => 'SMTP port', 'type' => 'number', 'help' => '587 (TLS) or 465 (SSL)'],
                ['k' => 'smtpUser', 'label' => 'SMTP username', 'type' => 'text'],
                ['k' => 'smtpPass', 'label' => 'SMTP password', 'type' => 'password', 'help' => 'leave empty to keep the saved one'],
                $toggle('smtpSecure', 'SSL', 'Use SSL (port 465)'),
                ['k' => 'fromEmail', 'label' => 'From address', 'type' => 'email', 'help' => 'usually the SMTP username'],
                ['k' => 'fromName', 'label' => 'From name', 'type' => 'text'],
            ]],
            'theme' => ['group' => 'theme', 'label' => 'Colours', 'icon' => 'i-layers', 'desc' => 'Brand colours used for buttons, highlights and accents.', 'fields' => [
                ['k' => 'brandLight', 'label' => 'Brand — light', 'type' => 'color'],
                ['k' => 'brand', 'label' => 'Brand — main', 'type' => 'color'],
                ['k' => 'brandDark', 'label' => 'Brand — dark (text & links)', 'type' => 'color'],
                ['k' => 'accent', 'label' => 'Accent (blue)', 'type' => 'color'],
            ]],
            'forms' => ['group' => 'forms', 'label' => 'Quote forms', 'icon' => 'i-inbox', 'desc' => 'What visitors see after sending a quote request.', 'fields' => [
                ['k' => 'successMessage', 'label' => 'Thank-you message', 'type' => 'textarea'],
                $toggle('offerWhatsapp', 'WhatsApp follow-up', 'Offer an “Also send on WhatsApp” button with the request pre-filled'),
            ]],
        ];
    }
}
