<?php

namespace App\Support;

/**
 * Site settings — defaults. Every group is stored as one JSON row in the
 * settings table and deep-merged over these values, so a new field added
 * here shows up immediately without a migration.
 */
class SettingsDefaults
{
    public static function all(): array
    {
        return [
            'general' => [
                'siteName' => 'Buses Transport UAE',
                'brandFirst' => 'Buses',
                'brandSecond' => 'Transport',
                'tagline' => 'Chauffeur & self-drive · UAE',
                'logo' => '',
                'logoHeight' => 42,
                'showWordmarkWithLogo' => false,
                'favicon' => '',
                'footerAbout' => 'Chauffeur-driven car, van and bus rental across Dubai and the UAE — airport transfers, city tours, corporate travel and long-term hire, available 24/7.',
                'footerLegal' => 'Car, van & bus rental in Dubai, Abu Dhabi & across the UAE',
                'copyright' => '© {year} Buses Transport In UAE. All rights reserved.',
                'siteUrl' => '',
                'showFloatingWhatsApp' => true,
                'showBlogInNav' => true,
            ],
            'contact' => [
                'headStripLocation' => 'Al Muteen, Dubai · Serving all 7 emirates',
                'phones' => ['+971 56 304 8829', '+971 50 463 2163'],
                'whatsapp' => '+971 52 736 6525',
                'whatsappMessage' => "Welcome to Buses Transport UAE! We're here to help you with car, van & bus rental across Dubai and the UAE. How can we assist you today?",
                'emails' => ['busestransportuae@gmail.com', 'booking@busestransport.com'],
                'address' => 'Residence 1072, Al Muteen, Abu Bakar Al Saqib Street, Dubai, UAE',
                'hours' => 'Available 24/7 — every day of the week',
                'hoursRows' => [
                    ['label' => 'Bookings & quotes', 'value' => '24 / 7'],
                    ['label' => 'Phone & WhatsApp support', 'value' => '24 / 7'],
                    ['label' => 'Airport transfers', 'value' => '24 / 7'],
                ],
                'mapEmbedUrl' => '',
                'contactTitle' => 'Talk to our team',
                'contactSub' => 'Call, WhatsApp or send us your trip details — our team will confirm your vehicle and an AED price across Dubai and the UAE.',
            ],
            'social' => [
                'facebook' => '', 'instagram' => '', 'tiktok' => '', 'linkedin' => '', 'youtube' => '', 'x' => '', 'googleReviews' => '',
            ],
            'home' => [
                'heroKicker' => 'Dubai & UAE ground transportation',
                'heroLine1' => 'Reliable car, van',
                'heroLine2' => '& bus rental in Dubai',
                'heroHighlight' => '& across the UAE.',
                'heroSub' => 'Daily and monthly vehicle rental with or without a driver. Airport transfers, city tours, hotel transfers, shuttle services, dinner transfers and group transportation.',
                'heroImage' => '/images/hero.jpg',
                'heroPrimaryLabel' => 'Browse the fleet',
                'heroPrimaryHref' => '/fleet',
                'heroSecondaryLabel' => 'See our services',
                'heroSecondaryHref' => '/services',
                'trust' => [
                    ['label' => 'Vehicle classes', 'value' => '17'],
                    ['label' => 'Seats available', 'value' => '4–50'],
                    ['label' => 'Dispatch & support', 'value' => '24/7'],
                    ['label' => 'Emirates covered', 'value' => '7'],
                ],
                'quoteTitle' => 'Get a free quote',
                'quoteBadge' => 'Fast AED quote',
                'quoteNote' => 'Rates are always quoted in AED, based on vehicle, route, duration and service.',
                'tickerExtras' => [
                    'Airport meet-and-greet|DXB · DWC · AUH · SHJ',
                    'Seats available|4 to 50',
                    'Daily & monthly rental|With or without driver',
                    'Booking & dispatch|24 / 7',
                ],
                'showTicker' => true,
                'servicesEyebrow' => 'Popular services',
                'servicesTitle' => 'Transportation services across the UAE',
                'servicesSub' => 'From airport pick-ups to monthly corporate contracts, Buses Transport UAE covers every kind of ground transport a traveller, family, hotel or company needs.',
                'showServices' => true,
                'fleetEyebrow' => 'Choose your vehicle',
                'fleetTitle' => 'Our fleet — sedan to 50-seater luxury bus',
                'fleetSub' => 'Executive cars, 7-seater family vans, luxury SUVs, group vans and buses up to 50 seats — most with a professional driver, selected vehicles available without a driver for self-drive hire.',
                'showFleet' => true,
                'whyEyebrow' => 'Why choose us',
                'whyTitle' => 'Built for reliable ground transport',
                'whySub' => 'Whether it’s a single airport transfer or a monthly contract for your company’s staff transportation, we run every trip the same way — on time, professionally driven and confirmed before you travel.',
                'why' => [
                    ['icon' => 'i-shield', 'title' => 'Professional service', 'body' => 'Licensed, courteous drivers on every booking, with self-drive available on selected vehicles.'],
                    ['icon' => 'i-bus', 'title' => 'Wide vehicle choice', 'body' => 'Sedan through to a 50-seat luxury coach — clean, well-maintained vehicles inspected before every trip.'],
                    ['icon' => 'i-calendar', 'title' => 'Daily & monthly rental', 'body' => 'Flexible terms for short trips or ongoing use, for companies and individuals.'],
                    ['icon' => 'i-pin', 'title' => 'Dubai & UAE coverage', 'body' => 'All seven emirates, including inter-emirate travel and every major airport.'],
                    ['icon' => 'i-users', 'title' => 'Group transportation', 'body' => 'Vans and coaches sized to your group, from families to large events and staff contracts.'],
                    ['icon' => 'i-whats', 'title' => 'Easy quote & booking', 'body' => 'Call, WhatsApp or use our quote form — fast AED pricing and 24/7 booking support.'],
                ],
                'showWhy' => true,
                'coverageEyebrow' => 'Dubai & UAE transportation',
                'coverageTitle' => 'Transportation across the UAE',
                'coverageSub' => 'We operate across Dubai, Abu Dhabi, Sharjah, Ajman, Umm Al Quwain, Ras Al Khaimah and Fujairah — for individual trips, group transport, and inter-emirate travel.',
                'showCoverage' => true,
                'stats' => [
                    ['n' => 17, 'suffix' => '', 'label' => 'Vehicle classes in the fleet', 'sub' => 'Sedan to 50-seater', 'dec' => 0],
                    ['n' => 50, 'suffix' => '', 'label' => 'Seats in our largest coach', 'sub' => 'Groups & events', 'dec' => 0],
                    ['n' => 7, 'suffix' => '', 'label' => 'Emirates covered', 'sub' => 'Plus inter-emirate routes', 'dec' => 0],
                    ['n' => 24, 'suffix' => '/7', 'label' => 'Booking & dispatch support', 'sub' => 'Phone & WhatsApp', 'dec' => 0],
                ],
                'showStats' => true,
                'stepsEyebrow' => 'How booking works',
                'stepsTitle' => 'Four simple steps to your booking',
                'stepsSub' => 'Rates are always quoted in AED, based on vehicle, route, duration and service — never a fixed online price.',
                'steps' => [
                    ['t' => 'Share your trip', 'b' => 'Send your pick-up point, destination, date, time and group size by phone, WhatsApp or the quote form.'],
                    ['t' => 'Get matched to a vehicle', 'b' => 'We recommend the right vehicle — or several — for your group, luggage and route.'],
                    ['t' => 'Confirm your AED price', 'b' => 'Your price and schedule are confirmed before you travel. No fixed online prices, no hidden charges.'],
                    ['t' => 'Travel with us', 'b' => 'Your driver arrives on time with a clean, air-conditioned vehicle, ready to go.'],
                ],
                'showSteps' => true,
                'reviewsEyebrow' => 'Customer reviews',
                'reviewsTitle' => 'What our clients say',
                'reviewsSub' => 'We’re building our public review collection as we complete more trips — read verified reviews on our Google Business Profile, or share your own experience.',
                'showReviews' => true,
                'blogEyebrow' => 'From our team',
                'blogTitle' => 'Guides for moving around the UAE',
                'blogSub' => 'Practical notes on airport transfers, choosing a vehicle and renting by the day or month.',
                'showBlog' => true,
                'ctaTitle' => 'Need a car, van or bus in Dubai?',
                'ctaSub' => 'Tell us your route, date and group size — we’ll confirm your vehicle and an AED price by phone or WhatsApp within minutes.',
                'ctaImage' => '/images/band-cta.jpg',
                'showCta' => true,
            ],
            'about' => [
                'title' => 'Reliable transportation across Dubai & the UAE',
                'sub' => 'Buses Transport UAE is a professional provider of car, van and bus rental services for individuals, families, tourists, hotels, companies and groups across Dubai and the wider UAE.',
                'body' => "## Your trusted transportation partner in the UAE\n\nBuses Transport UAE provides comfortable and dependable transportation solutions across the UAE. Customers can book vehicles for airport transfers, tours, hotel transfers, events, private travel, staff transportation and group travel.\n\nWe offer daily and monthly rental, with a professional driver on most bookings and selected vehicles available without a driver for self-drive hire. Every booking is confirmed in AED before you travel — **no fixed online prices, no hidden charges**.\n\n## Transportation wherever you need it\n\nWe operate across Dubai, Abu Dhabi, Sharjah, Ajman, Umm Al Quwain, Ras Al Khaimah and Fujairah, for individual trips, group transport and inter-emirate travel.\n\n## Comfort. Reliability. Professional service.\n\nWe focus on comfortable, well-maintained vehicles, dependable service, punctuality, clear communication and an easy booking experience — from your first message to the moment your driver arrives.",
                'panelTitle' => 'At a glance',
                'facts' => [
                    ['label' => 'Based in', 'value' => 'Dubai'],
                    ['label' => 'Vehicle classes', 'value' => '17'],
                    ['label' => 'Seating', 'value' => '4 to 50 seats'],
                    ['label' => 'Coverage', 'value' => 'All 7 emirates'],
                    ['label' => 'Bookings & support', 'value' => '24 / 7'],
                    ['label' => 'Pricing', 'value' => 'Quoted in AED'],
                ],
                'valuesTitle' => 'Built around what you need',
                'image' => '/images/band-cta.jpg',
            ],
            'seo' => [
                'titleTemplate' => '%s · Buses Transport UAE',
                'defaultTitle' => 'Buses Transport In UAE — Car, Van & Bus Rental Dubai',
                'description' => 'Buses Transport UAE offers bus rental Dubai, car rental Dubai with driver, van rental, airport transfer Dubai, staff transportation and daily/monthly rental across the UAE. Fleet from Sedan to 50-Seater Luxury Bus.',
                'keywords' => 'bus rental Dubai, car rental Dubai with driver, van rental Dubai, airport transfer Dubai, staff transportation UAE, 50 seater bus rental, Toyota Hiace rental Dubai, Toyota Coaster rental Dubai, monthly car rental UAE',
                'ogImage' => '/images/hero.jpg',
                'robotsIndex' => true,
                'googleVerification' => '',
                'bingVerification' => '',
                'businessType' => 'LocalBusiness',
                'pages' => [
                    'home' => ['title' => '', 'description' => '', 'keywords' => '', 'ogImage' => ''],
                    'services' => ['title' => 'Transportation Services in Dubai & the UAE', 'description' => 'Airport transfers, city tours, hotel transfers, shuttle services, dinner transfers, car and bus rental, daily and monthly hire across the UAE.', 'keywords' => '', 'ogImage' => ''],
                    'fleet' => ['title' => 'Our Vehicles — Sedan to 50-Seater Luxury Bus', 'description' => 'See the full Buses Transport UAE fleet: Sedan, Mercedes V-Class, Kia Carnival, Kia Sedona, Mercedes Sprinter, Toyota Hiace, Toyota Coaster, and 35 & 50-seater luxury buses.', 'keywords' => '', 'ogImage' => ''],
                    'coverage' => ['title' => 'UAE Coverage — All Seven Emirates', 'description' => 'Car, van and bus rental across Dubai, Abu Dhabi, Sharjah, Ajman, Umm Al Quwain, Ras Al Khaimah, Fujairah and Al Ain, including all major airports.', 'keywords' => '', 'ogImage' => ''],
                    'blog' => ['title' => 'Blog', 'description' => 'Guides on airport transfers, choosing the right vehicle and daily or monthly rental in the UAE.', 'keywords' => '', 'ogImage' => ''],
                    'about' => ['title' => 'About Us', 'description' => 'Buses Transport UAE is a professional car, van and bus rental company serving Dubai and the UAE — airport transfers, city tours, hotel transfers, corporate travel and daily/monthly rental.', 'keywords' => '', 'ogImage' => ''],
                    'contact' => ['title' => 'Contact Us', 'description' => 'Contact Buses Transport UAE by phone, WhatsApp or our online quote form for car, van and bus rental across Dubai and the UAE.', 'keywords' => '', 'ogImage' => ''],
                    'faq' => ['title' => 'Frequently Asked Questions', 'description' => "Frequently asked questions about Buses Transport UAE's car, van and bus rental services across Dubai and the UAE.", 'keywords' => '', 'ogImage' => ''],
                ],
            ],
            'tracking' => ['gtmId' => '', 'ga4Id' => '', 'metaPixelId' => '', 'headCode' => '', 'bodyCode' => ''],
            'email' => [
                'notifyEnabled' => false, 'notifyTo' => '', 'smtpHost' => '', 'smtpPort' => 587, 'smtpSecure' => false,
                'smtpUser' => '', 'smtpPass' => '', 'fromEmail' => '', 'fromName' => 'Buses Transport UAE website',
            ],
            'theme' => ['brandLight' => '#C9391F', 'brand' => '#B32C1C', 'brandDark' => '#9A2317', 'accent' => '#3983D8'],
            'forms' => [
                'successMessage' => 'Thank you — your request has been received. Our team will confirm your vehicle and an AED price shortly.',
                'offerWhatsapp' => true,
            ],
        ];
    }
}
